name: Workflow / Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: >
            Hello @${{ github.actor }}, thank you for submitting an issue! 🚀
          pr_message: >
            Hello @${{ github.actor }}, thank you for submitting a PR!
            We will respond as soon as possible.
